centr_osvita/common/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.HomePageView.as_view(), name='home'),
    url(r'^teachers/$', views.OurTeachersView.as_view(), name='teachers'),
    url(r'^statistics/$', views.StatisticsView.as_view(), name='statistics'),
    url(r'^math/$', views.MathView.as_view(), name='math'),
    url(r'^ukrainian/$', views.UkrainianView.as_view(), name='ukrainian'),
    url(r'^english/$', views.EnglishView.as_view(), name='english'),
    url(r'^history/$', views.HistoryView.as_view(), name='history'),
    url(r'^physics/$', views.PhysicsView.as_view(), name='physics'),
    url(r'^geography/$', views.GeographyView.as_view(), name='geography'),
    url(r'^biology/$', views.BiologyView.as_view(), name='biology'),
    url(r'^chemistry/$', views.ChemistryView.as_view(), name='chemistry'),
]

centr_osvita/quiz/urls.py
from .views import TestView, TestListView, QuizResultView, FinishQuizView, CancelTestView, ProfileReportsView
from django.conf.urls import url

urlpatterns = [
    url(r'^results/(?P<pk>\d+)$', QuizResultView.as_view(), name='admin-quiz-result'),
    url(r'^reports/(?P<pk>\d+)$', ProfileReportsView.as_view(), name='admin-profile-report'),
    url(r'^list/$', TestListView.as_view(), name='test-list'),
    url(r'^finish/(?P<pk>\d+)$', FinishQuizView.as_view(), name='quiz-finish'),
    url(r'^cancel/(?P<pk>\d+)$', CancelTestView.as_view(), name='quiz-cancel'),
    url(r'^(?P<pk>\d+)$', TestView.as_view(), name='test-detail'),
]

centr_osvita/users/urls.py
# -*- coding: utf-8 -*-

from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^register/$', views.RegisterView.as_view(), name='register'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
]

config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(settings.ADMIN_URL, include(admin.site.urls)),
    url(r'^', include("centr_osvita.common.urls", namespace="common")),
    url(r'^users/', include("centr_osvita.users.urls", namespace="users")),
    url(r'^quiz/', include("centr_osvita.quiz.urls", namespace="quiz")),
]

if settings.USE_SILK:
    urlpatterns += [
        url(r'^silk/', include('silk.urls', namespace='silk'))
    ]

if settings.USE_DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

centr_osvita/quiz/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from model_utils.models import TimeStampedModel
from polymorphic.models import PolymorphicModel
from model_utils.choices import Choices
import time

from centr_osvita.profiles.models import Profile

QUESTION_TYPES = Choices(
    (0, 'common', 'common'),
    (1, 'order', 'order'),
    (2, 'mapping', 'mapping'),
)


def question_image_path(instance, filename):
    dot_position = filename.find('.')
    return 'test_{0}/{1}'.format(str(instance.test.id),
                                    filename[:dot_position]+str(int(time.time()))+filename[dot_position:])


class Subject(models.Model):
    name = models.CharField(_('Subject name'), max_length=255, help_text=_('Maximum length is 255 symbols'))
    slug = models.SlugField(_('Slug name'))

    class Meta:
        verbose_name = _('Subject')
        verbose_name_plural = _('Subjects')

    def __str__(self):
        return self.name

    @property
    def ordered_statistic_by_year(self):
        return self.statistics.order_by('year__date')


class Year(models.Model):
    date = models.SmallIntegerField(_('Year info'))

    class Meta:
        verbose_name = _('Year')
        verbose_name_plural = _('Years')

    def __str__(self):
        return str(self.date)


class YearSubjectStatistics(models.Model):
    subject = models.ForeignKey(Subject, verbose_name=_('Subject'), on_delete=models.CASCADE, related_name='statistics')
    percent_c = models.IntegerField(_('Percent of pupils that have C mark'))
    percent_b = models.IntegerField(_('Percent of pupils that have B mark'))
    percent_a = models.IntegerField(_('Percent of pupils that have A mark'))
    year = models.ForeignKey(Year, verbose_name=_('Year'), on_delete=models.CASCADE, related_name='statistics')

    class Meta:
        verbose_name = _('Year Subject Statisctic')
        verbose_name_plural = _('Year Subject Statisctics')


class TestParameter(TimeStampedModel):
    test_time = models.SmallIntegerField(_('Test time'), default=20)
    number_of_common_questions =  models.SmallIntegerField(_('Number of common questions'))
    number_of_order_questions = models.SmallIntegerField(_('Number of order questions'))
    number_of_mapping_questions = models.SmallIntegerField(_('Number of mapping questions'))
    coefficient_of_common_question = models.FloatField(_('coefficient per common questions'))
    coefficient_of_order_question = models.FloatField(_('coefficient per order questions'))
    coefficient_of_mapping_question = models.FloatField(_('coefficient per mapping questions'))

    class Meta:
        verbose_name = _('Test Parameter')
        verbose_name_plural = _('Test Parameters')


class Test(TimeStampedModel):
    subject = models.ForeignKey(Subject, verbose_name=_('Subject'), on_delete=models.CASCADE, related_name='tests')
    name = models.CharField(_('Test name'), max_length=255, help_text=_('Maximum length is 255 symbols'))
    status = models.BooleanField(_('Publish status'))
    test_parameter = models.OneToOneField(TestParameter, verbose_name=_('Test Parameter'), on_delete=models.CASCADE)

    class Meta:
        verbose_name = _('Test')
        verbose_name_plural = _('Tests')

    def __str__(self):
        return '{} {}'.format(self.subject.name, self.name)

class Question(TimeStampedModel):
    test = models.ForeignKey(Test, verbose_name=_('Test'), on_delete=models.CASCADE, related_name='questions')
    text = models.TextField(_('Text'))
    image = models.ImageField(_("Image"), upload_to=question_image_path, null=True, blank=True)
    type = models.IntegerField(_("Question Type"), choices=QUESTION_TYPES, default=QUESTION_TYPES.common)

    class Meta:
        verbose_name = _('Question')
        verbose_name_plural = _('Questions')

    def __str__(self):
        return self.text[:20]

    @property
    def ordered_answers_by_position(self):
        answers_ids = self.answer_set.values_list('id', flat=True)
        if self.type == QUESTION_TYPES.common:
            return CommonAnswer.objects.filter(id__in=answers_ids).order_by('number')
        elif self.type == QUESTION_TYPES.order:
            return OrderAnswer.objects.filter(id__in=answers_ids).order_by('number_1')
        if self.type == QUESTION_TYPES.mapping:
            return MappingAnswer.objects.filter(id__in=answers_ids).order_by('number_1')
        return self.answer_set

    @property
    def ordered_answers_by_position_two(self):
        answers_ids = self.answer_set.values_list('id', flat=True)
        if self.type == QUESTION_TYPES.common:
            return CommonAnswer.objects.filter(id__in=answers_ids).order_by('number')
        elif self.type == QUESTION_TYPES.order:
            return OrderAnswer.objects.filter(id__in=answers_ids).order_by('number_2')
        if self.type == QUESTION_TYPES.mapping:
            return MappingAnswer.objects.filter(id__in=answers_ids).order_by('number_2')
        return self.answer_set


# Needs to correct deletion
# Workaround https://github.com/django-polymorphic/django-polymorphic/issues/229#issuecomment-398434412
def NON_POLYMORPHIC_CASCADE(collector, field, sub_objs, using):
    return models.CASCADE(collector, field, sub_objs.non_polymorphic(), using)


class Answer(PolymorphicModel, TimeStampedModel):
    question = models.ForeignKey(Question, verbose_name=_('Question'), on_delete=NON_POLYMORPHIC_CASCADE)

    class Meta:
        verbose_name = _('Answer')
        verbose_name_plural = _('Answers')

    @property
    def type(self):
        return self._meta.object_name

    def __str__(self):
        return str(self.id)


class CommonAnswer(Answer):
    ORDER_COMMON = Choices(
        (1, 'first', 'A'),
        (2, 'second', 'B'),
        (3, 'third', 'C'),
        (4, 'fourth', 'D'),
        (5, 'fifth', 'E'),
    )
    text = models.CharField(_('Text'), max_length=255)
    number = models.IntegerField(_("Answer Order"), choices=ORDER_COMMON)
    correct = models.BooleanField(_('Correct answer'))

    class Meta:
        verbose_name = _('Common Answer')
        verbose_name_plural = _('Common Answers')

    def __str__(self):
        return '{}__{}:{}'.format(self.question.id, self.id, self.number)


class OrderAnswer(Answer):
    ORDER_FIRST_CHAIN = Choices(
        (1, 'first', '1'),
        (2, 'second', '2'),
        (3, 'third', '3'),
        (4, 'fourth', '4'),
    )
    ORDER_SECOND_CHAIN = Choices(
        (1, 'first', 'A'),
        (2, 'second', 'B'),
        (3, 'third', 'C'),
        (4, 'fourth', 'D'),
    )

    text = models.CharField(_('Text'), max_length=255)
    number_1 = models.IntegerField(_("Answer FIRST Position"), choices=ORDER_FIRST_CHAIN)
    number_2 = models.IntegerField(_("Answer SECOND Position"), choices=ORDER_SECOND_CHAIN)

    class Meta:
        verbose_name = _('Order Answer')
        verbose_name_plural = _('Order Answers')

    def __str__(self):
        return '{}__{}:{}_{}'.format(self.question.id, self.id, self.number_1, self.number_2)


class MappingAnswer(Answer):
    FIRST_CHAIN_TYPES = Choices(
        (1, 'first', '1'),
        (2, 'second', '2'),
        (3, 'third', '3'),
        (4, 'fourth', '4'),
        (0, 'zero', '0'),
    )
    SECOND_CHAIN_TYPES = Choices(
        (1, 'first', 'A'),
        (2, 'second', 'B'),
        (3, 'third', 'C'),
        (4, 'fourth', 'D'),
        (5, 'fifth', 'E'),
    )

    number_1 = models.IntegerField(_("First chain"), choices=FIRST_CHAIN_TYPES)
    number_2 = models.IntegerField(_("Second chain"), choices=SECOND_CHAIN_TYPES)
    text_1 = models.CharField(_('Text 1'), null=True, blank=True, max_length=255)
    text_2 = models.CharField(_('Text 2'), max_length=255)

    class Meta:
        verbose_name = _('Mapping Answer')
        verbose_name_plural = _('Mapping Answers')

    def __str__(self):
        return '{}__{}:{}_{}'.format(self.question.id, self.id, self.number_1, self.number_2)


class Quiz(TimeStampedModel):
    QUIZ_STATUS_TYPES = Choices(
        (0, 'progress', 'In Progress'),
        (1, 'done', 'Done'),
        (2, 'suspend', 'Suspend'),
    )
    test = models.ForeignKey(Test, verbose_name=_('Test'), on_delete=models.CASCADE, related_name='quizzes')
    status = models.IntegerField(_("Status"), choices=QUIZ_STATUS_TYPES, default=QUIZ_STATUS_TYPES.progress)
    student = models.ForeignKey(Profile, verbose_name=_('Student'), on_delete=models.CASCADE, related_name='quizzes')

    class Meta:
        verbose_name = _('Quiz')
        verbose_name_plural = _('Quizzes')

    def __str__(self):
        return '{}:{}_{}'.format(self.id, self.test.name, self.student.full_name)

    def create_random_quiz_questions(self):
        common_questions = Question.objects.filter(
            test=self.test,
            type=QUESTION_TYPES.common).order_by('?')[:self.test.test_parameter.number_of_common_questions]
        order_questions = Question.objects.filter(
            test=self.test,
            type=QUESTION_TYPES.order).order_by('?')[:self.test.test_parameter.number_of_order_questions]
        mapping_questions = Question.objects.filter(
            test=self.test,
            type=QUESTION_TYPES.mapping).order_by('?')[:self.test.test_parameter.number_of_mapping_questions]

        for common in common_questions:
            QuizQuestion.objects.create(question=common, quiz=self)

        for order in order_questions:
            QuizQuestion.objects.create(question=order, quiz=self)

        for mapping in mapping_questions:
            QuizQuestion.objects.create(question=mapping, quiz=self)


    @property
    def question_sum_common_order(self):
        return self.common_quiz_questions.count() + self.order_quiz_questions.count()

    @property
    def max_available_mark(self):
        max_mark = self.common_quiz_questions.count()*self.test.test_parameter.coefficient_of_common_question \

centr_osvita/profiles/forms.py
from django import forms
from django.forms import ModelForm
from centr_osvita.profiles.models import Profile


class ProfileRegisterForm(ModelForm):
    grade = forms.ChoiceField(choices=Profile.GRADE_NUMBER, initial=Profile.GRADE_NUMBER.nine, required=False)

    class Meta:
        model = Profile
        fields = ['full_name', 'parent_full_name', 'parent_phone', 'institution_type', 'institution_name', 'grade']

    def __init__(self, *args, **kwargs):
        user = kwargs.get('user', None)
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    def clean(self):
        cleaned_data = super().clean()
        return cleaned_data

    def save(self, commit=True):
        instance = super().save(commit=False)
        if not instance.grade:
            instance.grade = None
        instance.user = self.user

        if commit:
            instance.save()
        return instance

centr_osvita/common/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.utils.translation import ugettext as _
from django.views.generic import View
from django.views.generic.base import TemplateView
from django.conf import settings
from django.http.response import HttpResponse
from django.http import Http404
from centr_osvita.quiz.models import Subject


class HealthCheckView(View):

    def get(self, request, *args, **kwargs):
        return HttpResponse(settings.HEALTH_CHECK_BODY, status=200)


class HomePageView(TemplateView):
    template_name = "web/home.html"


class OurTeachersView(TemplateView):
    template_name = "web/ourTeachers.html"


class StatisticsView(View):
    template_name = "web/statistics.html"
    param = None
    subject = None

    def dispatch(self, request, *args, **kwargs):
        param = self.request.GET.get('subject')
        self.subject = Subject.objects.filter(slug=param).first()
        if not self.subject:
            raise Http404(_("Not found"))
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        context = dict()
        context['subject'] = self.subject
        return render(request, self.template_name, context)


class MathView(TemplateView):
    template_name = "web/math.html"


class UkrainianView(TemplateView):
    template_name = "web/ukrainian.html"


class EnglishView(TemplateView):
    template_name = "web/english.html"


class HistoryView(TemplateView):
    template_name = "web/history.html"


class PhysicsView(TemplateView):
    template_name = "web/physics.html"


class GeographyView(TemplateView):
    template_name = "web/geography.html"


class BiologyView(TemplateView):
    template_name = "web/biology.html"


class ChemistryView(TemplateView):
    template_name = "web/chemistry.html"

centr_osvita/profiles/views.py
from django.shortcuts import render

# Create your views here.

centr_osvita/users/views.py
# -*- coding: utf-8 -*-

from __future__ import absolute_import, unicode_literals

from django.contrib.auth import logout, login
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect
from django.views.generic import View

from centr_osvita.profiles.forms import ProfileRegisterForm
from centr_osvita.users.forms import UserRegisterForm


class RegisterView(View):
    template_name = 'auth/register.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('common:home')
        return render(request, self.template_name, {'user_form': UserRegisterForm, 'profile_form': ProfileRegisterForm})

    def post(self, request, *args, **kwargs):
        user_form = UserRegisterForm(data=request.POST)
        profile_form = ProfileRegisterForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile_form.user = user
            profile_form.save()
            login(request, user)
            return redirect('common:home')

        return render(request, self.template_name, {'user_form': user_form, 'profile_form': profile_form})


class LoginView(View):
    template_name = 'auth/login.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('common:home')
        return render(request, self.template_name, {'form': AuthenticationForm})

    def post(self, request, *args, **kwargs):
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('common:home')
        else:
            return render(request, self.template_name, {'form': form})


def logout_view(request):
    logout(request)
    response = redirect('common:home')
    return response

centr_osvita/templates/quiz/reports.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}Результати{% endblock title %}</title>
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <link
      rel="shortcut icon"
      href="{% static 'images/COT_Logo_Title.png' %}"
      type="image/png"
    />
    {% block css %}
    <link href="{% static 'css/results.css' %}" rel="stylesheet" />
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" />
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet" />
    {% endblock %}
  </head>
  <body>
    <div class="results">
      <p>Дата звіту: {{ object.created }}</p>

      {% block content %} {% for student in object.ordered_by_student_full_name.all %}
      <table class="table table-bordered">
        <thead class="text-center">
          <tr>
            <th scope="col">Прізвище ім'я</th>
            <th scope="col">Номер телефону</th>
            <th scope="col">Ім'я одного з батьків</th>
            <th scope="col">Номер одного з батьків</th>
            <th scope="col">Клас</th>
          </tr>
        </thead>

        <tr>
          <td>{{student.full_name}}</td>
          <td>{{student.user.phone}}</td>
          <td>{{student.parent_full_name}}</td>
          <td>{{student.parent_phone}}</td>
          {% if student.grade %}
          <td>{{student.grade}}</td>
          {% else %}
          <td>-</td>
          {% endif %}
        </tr>
      </table>

      {% if student.quizzes.all %}
      <table class="table table-bordered">
        <thead class="text-center">
          <tr>
            <th scope="col">Пройдені тести</th>
            <th scope="col">Дата і час</th>
            <th scope="col">Оцінка</th>
          </tr>
        </thead>

        {% for quiz in student.quizzes.all %}
        <tr>
          <td>{{ quiz.test.subject.name }} {{ quiz.test.name }}</td>
          <td>{{quiz.created|date:"d.m.Y: H:i"}}</td>
          <td>{{ quiz.current_mark }}/{{ quiz.max_available_mark }}</td>
        </tr>
        {% endfor %}
      </table>

      {% endif %} {% endfor %} {% endblock content %}

      <input
        type="button"
        name="print"
        value="Print"
        class="btn btn-primary"
        onclick="window.print()"
      />
    </div>

    {% block modal %}{% endblock modal %} {% block javascript %}
    <script src="{% static 'js/jquery-2.2.0.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/project.js' %}"></script>
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: ["Roboto+Slab::cyrillic"] }
      };
      (function() {
        var wf = document.createElement("script");
        wf.src = "{% static 'js/webfont.js'%}";
        wf.type = "text/javascript";
        wf.async = "true";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
    {% endblock javascript %}
  </body>
</html>

centr_osvita/templates/quiz/subject_list.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}Список тестів{% endblock %}

{% block content %}

<main>
    <div class="content">
        <div class="quiz-list">
            <h1>Тести</h1>
            <form action="{% url 'quiz:subject-list' %}"
                  method="get"
                  class="quiz-list__search">
                <input name="q"
                       type="text"
                       placeholder="Пошук..."
                       aria-label="Пошук..."
                       class="form-control"
                       aria-describedby="button-addon2">
            </form>

            <div class="quiz-list__list">
                {% for subject in object_list %}
                <a href="{% url 'quiz:subject-detail' subject.id %}">
                    {{ subject.name }}
                </a>
                {% endfor %}
            </div>
        </div>
    </div>
</main>

{% endblock %}

centr_osvita/templates/quiz/test_detail.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}{{object.name}}{% endblock %}


{% block content %}
<main>
    <div class="content">
        <div class="quiz-detail">
            <div class="quiz-detail__head">
                <h4 class="quiz-detail__question" data-question-id="{{ question.id }}">
                    {{ question.text }}
                </h4>
<!--                Enter time here in seconds-->
                <p id="time">{{ time_left }}</p>
                <p id="timer"></p>
                 <form action="{% url 'quiz:quiz-cancel' quiz.id%}" method="post">
                     {% csrf_token %}
                    <p>
                        <input type="submit"
                               value="Зупинити тест"
                               class="btn btn-primary quiz-detail__stop-btn">
                    </p>
                 </form>
            </div>


            {% if question.image %}
                <div class="quiz-detail__image">
                    <img src="{{ question.image.url }}"
                         alt="Image"/>
                </div>
            {% endif %}

            <div class="quiz-detail__answer-list">
                {% if question.type == 0 %}
                {% for answer in question.ordered_answers_by_position.all %}
                <p data-answer-id="{{ answer.id }}">
                    {{answer.get_number_display}}. {{answer.text}}
                </p>
                {% endfor %}
                {% elif question.type == 1 %}
                {% for answer in question.ordered_answers_by_position_two.all %}
                <p data-answer-id="{{ answer.id }}">
                    {{answer.get_number_2_display}}. {{answer.text}}
                </p>
                {% endfor %}
                {% else %}
                <div class="tables-flex">
                    <table border="1">
                        {% for answer in question.ordered_answers_by_position.all %}
                        {% if answer.number_1 != 0 %}
                        <tr>
                            <td data-answer-id="{{ answer.id }}">
                                {{answer.get_number_1_display}}
                            </td>
                            <td>
                                {{answer.text_1}}
                            </td>
                        </tr>
                        {% endif %}
                        {% endfor %}
                    </table>

                    <table border="1">
                        {% for answer in question.ordered_answers_by_position_two.all %}
                        <tr>
                            <td>
                                {{answer.get_number_2_display}}
                            </td>
                            <td>
                                {{answer.text_2}}
                            </td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
                {% endif %}
            </div>

            <div class="quiz-detail__result-table">
                <form action="{% url 'quiz:test-detail' object.id%}"
                      method="post" class="quiz-detail__result-form">
                    {% csrf_token %}
                    {{ formset.management_form }}
                    {{ formset.non_form_errors }}
                    <table border="1">
                        {% if question.type == 2 %}
                        <tr>
                            <td> </td>
                            {% for answer in question.ordered_answers_by_position_two.all %}
                            <td>{{answer.get_number_2_display}}</td>
                            {% endfor %}
                        </tr>
                        {% for form in formset %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            {% for field in form %}
                            {% for radio in field %}
                            <td class="myradio">
                                <label for="{{ radio.id_for_label }}"
                                       class="order-wrapper">
                                    {{ radio.tag }}
                                    <span class="checkmark"></span>
                                </label>
                            </td>
                            {% endfor %}
                        </tr>
                        {% endfor %}
                        {% endfor %}
                        {% elif question.type == 1 %}
                        <tr>
                            <td> </td>
                            {% for answer in question.ordered_answers_by_position_two.all %}
                            <td>{{answer.get_number_2_display}}</td>
                            {% endfor %}
                        </tr>
                        {% for form in formset %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            {% for field in form %}
                            {% for radio in field %}
                            <td class="myradio">
                                <label for="{{ radio.id_for_label }}"
                                       class="order-wrapper">
                                    {{ radio.tag }}
                                    <span class="checkmark"></span>
                                </label>
                            </td>
                            {% endfor %}
                        </tr>
                        {% endfor %}
                        {% endfor %}
                        {% else %}
                        <tr>
                            {% for answer in question.ordered_answers_by_position_two.all %}
                            <td>{{answer.get_number_display}}</td>
                            {% endfor %}
                        </tr>
                        <tr>
                            {% for form in formset %}
                            {% for field in form %}
                            {% for radio in field %}
                            <td class="myradio">
                                <label for="{{ radio.id_for_label }}"
                                       class="order-wrapper">
                                    {{ radio.tag }}
                                    <span class="checkmark"></span>
                                </label>
                            </td>
                            {% endfor %}
                            {% endfor %}
                            {% endfor %}
                        </tr>
                        {% endif %}
                    </table>

                    <input type="submit"
                           value="Надіслати"
                           class="btn btn-primary">
                </form>
            </div>


        </div>
    </div>
</main>
<!-- Modal -->
<div class="modal fade" id="timeoutModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                Час вичерпано
            </div>
            <div class="modal-footer">
<!--                Set results link here-->
                <a href="{% url 'quiz:quiz-finish' quiz.id%}" class="btn btn-primary" id="timeout-results">Результати</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

centr_osvita/templates/quiz/test_ending.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}Список тестів{% endblock %}


{% block content %}
<main>
    <div class="container">
        <div class="quiz-detail quiz-detail--end">
            <h1>Ви пройшли тест!</h1>
            <h4>Результат: {{ instance.current_mark }}/{{ instance.max_available_mark }}</h4>
            <div>
                <p class="quiz-detail__contact-link">Для консультації звертайтеся за <a href="{% url 'common:home' %}#contacts">контактами</a>.</p>
            </div>
            <a href="{% url 'common:home' %}"
               class="btn btn-primary">
                Повернутись на головну
            </a>
        </div>
    </div>
</main>

{% endblock %}

centr_osvita/templates/quiz/test_list.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}Список тестів{% endblock %}

{% block content %}

<main>
    <div class="content">
        <div class="quiz-list">
            <h1>Тести</h1>
            <div class="quiz-list__list">
                {% for subject in object_list %}
                <a href="{% url 'quiz:test-detail' subject.id %}">
                    {{ subject.name }}
                </a>
                {% endfor %}
            </div>
        </div>
    </div>
</main>

{% endblock %}