centr_osvita/common/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.HomePageView.as_view(), name='home'),
    url(r'^teachers/$', views.OurTeachersView.as_view(), name='teachers'),
    url(r'^statistics/$', views.StatisticsView.as_view(), name='statistics'),
    url(r'^math/$', views.MathView.as_view(), name='math'),
    url(r'^ukrainian/$', views.UkrainianView.as_view(), name='ukrainian'),
    url(r'^english/$', views.EnglishView.as_view(), name='english'),
    url(r'^history/$', views.HistoryView.as_view(), name='history'),
    url(r'^physics/$', views.PhysicsView.as_view(), name='physics'),
    url(r'^geography/$', views.GeographyView.as_view(), name='geography'),
    url(r'^biology/$', views.BiologyView.as_view(), name='biology'),
    url(r'^chemistry/$', views.ChemistryView.as_view(), name='chemistry'),
]

centr_osvita/quiz/urls.py
from .views import TestView, TestListView, QuizResultView, FinishQuizView, CancelTestView, ProfileReportsView
from django.conf.urls import url

urlpatterns = [
    url(r'^results/(?P<pk>\d+)$', QuizResultView.as_view(), name='admin-quiz-result'),
    url(r'^reports/(?P<pk>\d+)$', ProfileReportsView.as_view(), name='admin-profile-report'),
    url(r'^list/$', TestListView.as_view(), name='test-list'),
    url(r'^finish/(?P<pk>\d+)$', FinishQuizView.as_view(), name='quiz-finish'),
    url(r'^cancel/(?P<pk>\d+)$', CancelTestView.as_view(), name='quiz-cancel'),
    url(r'^(?P<pk>\d+)$', TestView.as_view(), name='test-detail'),
]

centr_osvita/users/urls.py
# -*- coding: utf-8 -*-

from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^register/$', views.RegisterView.as_view(), name='register'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
]

config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(settings.ADMIN_URL, include(admin.site.urls)),
    url(r'^', include("centr_osvita.common.urls", namespace="common")),
    url(r'^users/', include("centr_osvita.users.urls", namespace="users")),
    url(r'^quiz/', include("centr_osvita.quiz.urls", namespace="quiz")),
]

if settings.USE_SILK:
    urlpatterns += [
        url(r'^silk/', include('silk.urls', namespace='silk'))
    ]

if settings.USE_DEBUG_TOOLBAR:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

centr_osvita/profiles/forms.py
from django import forms
from django.forms import ModelForm
from centr_osvita.profiles.models import Profile


class ProfileRegisterForm(ModelForm):
    grade = forms.ChoiceField(choices=Profile.GRADE_NUMBER, initial=Profile.GRADE_NUMBER.nine, required=False)

    class Meta:
        model = Profile
        fields = ['full_name', 'parent_full_name', 'parent_phone', 'institution_type', 'institution_name', 'grade']

    def __init__(self, *args, **kwargs):
        user = kwargs.get('user', None)
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    def clean(self):
        cleaned_data = super().clean()
        return cleaned_data

    def save(self, commit=True):
        instance = super().save(commit=False)
        if not instance.grade:
            instance.grade = None
        instance.user = self.user

        if commit:
            instance.save()
        return instance

centr_osvita/common/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.utils.translation import ugettext as _
from django.views.generic import View
from django.views.generic.base import TemplateView
from django.conf import settings
from django.http.response import HttpResponse
from django.http import Http404
from centr_osvita.quiz.models import Subject


class HealthCheckView(View):

    def get(self, request, *args, **kwargs):
        return HttpResponse(settings.HEALTH_CHECK_BODY, status=200)


class HomePageView(TemplateView):
    template_name = "web/home.html"


class OurTeachersView(TemplateView):
    template_name = "web/ourTeachers.html"


class StatisticsView(View):
    template_name = "web/statistics.html"
    param = None
    subject = None

    def dispatch(self, request, *args, **kwargs):
        param = self.request.GET.get('subject')
        self.subject = Subject.objects.filter(slug=param).first()
        if not self.subject:
            raise Http404(_("Not found"))
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        context = dict()
        context['subject'] = self.subject
        return render(request, self.template_name, context)


class MathView(TemplateView):
    template_name = "web/math.html"


class UkrainianView(TemplateView):
    template_name = "web/ukrainian.html"


class EnglishView(TemplateView):
    template_name = "web/english.html"


class HistoryView(TemplateView):
    template_name = "web/history.html"


class PhysicsView(TemplateView):
    template_name = "web/physics.html"


class GeographyView(TemplateView):
    template_name = "web/geography.html"


class BiologyView(TemplateView):
    template_name = "web/biology.html"


class ChemistryView(TemplateView):
    template_name = "web/chemistry.html"

centr_osvita/profiles/views.py
from django.shortcuts import render

# Create your views here.

centr_osvita/quiz/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import formset_factory
from django.views.generic import ListView, View
from django.views.generic.detail import DetailView
from django.http import Http404
from django.utils.translation import ugettext as _
from django.shortcuts import render, redirect
from django.utils import timezone
from datetime import timedelta

from centr_osvita.quiz.forms import AnswerForm, OrderAnswerForm, AnswerValidatedFormSet
from centr_osvita.quiz.mixins import IsStaffRequiredMixin
from centr_osvita.quiz.models import Quiz, Test, Question, QUESTION_TYPES, QuizCommonAnswer, \
    QuizOrderAnswer, OrderAnswer, QuizMappingAnswer, MappingAnswer, QuizQuestion, CommonAnswer
from centr_osvita.profiles.models import UserReport


class QuizResultView(IsStaffRequiredMixin, DetailView):
    model = Quiz
    template_name = 'quiz/results.html'
    queryset = Quiz.objects.filter(status__in=(Quiz.QUIZ_STATUS_TYPES.suspend, Quiz.QUIZ_STATUS_TYPES.done))


class ProfileReportsView(IsStaffRequiredMixin, DetailView):
    model = UserReport
    template_name = 'quiz/reports.html'
    queryset = UserReport.objects.all()


class TestListView(LoginRequiredMixin, ListView):
    model = Test
    template_name = 'quiz/test_list.html'

    def get_queryset(self):
        subject_param = self.request.GET.get('subject')
        object_list = Test.objects.filter(status=True)
        if subject_param:
            object_list = object_list.filter(subject__slug=subject_param)
        return object_list


class TestView(LoginRequiredMixin, View):
    template_name = 'quiz/test_detail.html'
    current_question = None
    current_quiz = None
    instance = None
    current_formset = None

    def dispatch(self, request, *args, **kwargs):
        pk = self.kwargs.get('pk')
        self.instance = Test.objects.filter(pk=pk, status=True).first()
        if not self.instance:
            raise Http404(_("Not found"))
        if not Quiz.objects.filter(student=request.user.profile, status=Quiz.QUIZ_STATUS_TYPES.progress).count():
            quiz = Quiz.objects.create(test=self.instance, student=request.user.profile)
            quiz.create_random_quiz_questions()

        self.current_quiz = Quiz.objects.filter(student=self.request.user.profile,
                                                status=Quiz.QUIZ_STATUS_TYPES.progress).first()
        available_question_ids = self.current_quiz.quiz_questions.filter(
            status=QuizQuestion.QUIZ_QUESTION_STATUS_TYPES.active).values_list('question__id', flat=True)

        self.current_question = Question.objects.filter(test=self.instance, type=QUESTION_TYPES.common).filter(
            id__in=available_question_ids).first()
        if not self.current_question:
            self.current_question = Question.objects.filter(test=self.instance, type=QUESTION_TYPES.order).filter(
                id__in=available_question_ids).first()
        if not self.current_question:
            self.current_question = Question.objects.filter(test=self.instance, type=QUESTION_TYPES.mapping).filter(
                id__in=available_question_ids).first()

        self.current_formset = None
        if self.current_question is not None:
            if self.current_question.type == QUESTION_TYPES.common:
                CommonAnswerFormSet = formset_factory(AnswerForm)
                self.current_formset = CommonAnswerFormSet()
            elif self.current_question.type == QUESTION_TYPES.order:
                OrderAnswerFormSet = formset_factory(OrderAnswerForm, formset=AnswerValidatedFormSet,
                                                     extra=self.current_question.answer_set.count())
                self.current_formset = OrderAnswerFormSet()
            else:
                MappingAnswerFormSet = formset_factory(AnswerForm, formset=AnswerValidatedFormSet,
                                                       extra=self.current_question.ordered_answers_by_position.exclude(
                                                           number_1=MappingAnswer.FIRST_CHAIN_TYPES.zero).count())
                self.current_formset = MappingAnswerFormSet()

        if not self.current_question:
            return redirect('quiz:quiz-finish', self.current_quiz.id)

        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        context = dict()
        context['object'] = self.instance
        context['question'] = self.current_question
        context['quiz'] = self.current_quiz
        context['formset'] = self.current_formset
        if timezone.now() < self.current_quiz.created + \
                timedelta(minutes=self.current_quiz.test.test_parameter.test_time):
            context['time_left'] = int((self.current_quiz.created +
                                    timedelta(minutes=self.current_quiz.test.test_parameter.test_time) -
                                    timezone.now()).total_seconds())
        else:
            context['time_left'] = 0
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        context = dict()
        formset = None
        order_chain_list = ['first', 'second', 'third', 'fourth']
        if self.current_question is not None:
            if self.current_question.type == QUESTION_TYPES.common:
                CommonAnswerFormSet = formset_factory(AnswerForm)
                formset = CommonAnswerFormSet(request.POST)
            elif self.current_question.type == QUESTION_TYPES.order:
                OrderAnswerFormSet = formset_factory(OrderAnswerForm, formset=AnswerValidatedFormSet,
                                                     extra=self.current_question.answer_set.count())
                formset = OrderAnswerFormSet(request.POST)
            else:
                MappingAnswerFormSet = formset_factory(AnswerForm, formset=AnswerValidatedFormSet,
                                                       extra=self.current_question.ordered_answers_by_position.exclude(
                                                           number_1=MappingAnswer.FIRST_CHAIN_TYPES.zero).count())
                formset = MappingAnswerFormSet(request.POST)

        if formset.is_valid():
            quiz_question = QuizQuestion.objects.filter(quiz=self.current_quiz, question=self.current_question,
                                                        status=QuizQuestion.QUIZ_QUESTION_STATUS_TYPES.active).first()
            quiz_question.status = QuizQuestion.QUIZ_QUESTION_STATUS_TYPES.done
            quiz_question.save()
            answers_ids = self.current_question.answer_set.values_list('id', flat=True)
            if self.current_question.type == QUESTION_TYPES.common:
                answer = CommonAnswer.objects.filter(id__in=answers_ids,
                                                     number=formset.cleaned_data[0]['position']).first()
                QuizCommonAnswer.objects.create(quiz_question=quiz_question, number=formset.cleaned_data[0]['position'],
                                                answer=answer)
            elif self.current_question.type == QUESTION_TYPES.order:
                for key, form_data in enumerate(formset.cleaned_data):
                    answer = OrderAnswer.objects.filter(id__in=answers_ids,
                                                        number_1=getattr(OrderAnswer.ORDER_FIRST_CHAIN,
                                                                         order_chain_list[key])).first()
                    QuizOrderAnswer.objects.create(quiz_question=quiz_question,
                                                   number_2=form_data['position'],
                                                   number_1=answer.number_1, answer=answer)
            else:
                key_list = []
                for key, form_data in enumerate(formset.cleaned_data):
                    key_list.append(int(form_data['position']))
                    answer = MappingAnswer.objects.filter(id__in=answers_ids,
                                                          number_1=getattr(MappingAnswer.FIRST_CHAIN_TYPES,
                                                                           order_chain_list[key])).first()
                    QuizMappingAnswer.objects.create(quiz_question=quiz_question,
                                                     number_2=form_data['position'],
                                                     number_1=answer.number_1, answer=answer)

                answers_zero_position_one = MappingAnswer.objects.filter(
                    id__in=answers_ids, number_1=MappingAnswer.FIRST_CHAIN_TYPES.zero)
                second_order_list = []
                for key, value in MappingAnswer.SECOND_CHAIN_TYPES:
                    second_order_list.append(key)
                unused_second_key_list = [x for x in second_order_list if x not in key_list]

                for key, zero_answer in enumerate(answers_zero_position_one):
                    QuizMappingAnswer.objects.create(quiz_question=quiz_question, number_2=unused_second_key_list[key],
                                                     number_1=zero_answer.number_1, answer=zero_answer)

            return redirect('quiz:test-detail', self.instance.id)
        else:
            context['formset'] = formset
            context['object'] = self.instance
            context['question'] = self.current_question
            context['quiz'] = self.current_quiz
            if timezone.now() < self.current_quiz.created + \
                    timedelta(minutes=self.current_quiz.test.test_parameter.test_time):
                context['time_left'] = int((self.current_quiz.created +
                                        timedelta(minutes=self.current_quiz.test.test_parameter.test_time) -
                                        timezone.now()).total_seconds())
            else:

centr_osvita/users/views.py
# -*- coding: utf-8 -*-

from __future__ import absolute_import, unicode_literals

from django.contrib.auth import logout, login
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect
from django.views.generic import View

from centr_osvita.profiles.forms import ProfileRegisterForm
from centr_osvita.users.forms import UserRegisterForm


class RegisterView(View):
    template_name = 'auth/register.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('common:home')
        return render(request, self.template_name, {'user_form': UserRegisterForm, 'profile_form': ProfileRegisterForm})

    def post(self, request, *args, **kwargs):
        user_form = UserRegisterForm(data=request.POST)
        profile_form = ProfileRegisterForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile_form.user = user
            profile_form.save()
            login(request, user)
            return redirect('common:home')

        return render(request, self.template_name, {'user_form': user_form, 'profile_form': profile_form})


class LoginView(View):
    template_name = 'auth/login.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('common:home')
        return render(request, self.template_name, {'form': AuthenticationForm})

    def post(self, request, *args, **kwargs):
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('common:home')
        else:
            return render(request, self.template_name, {'form': form})


def logout_view(request):
    logout(request)
    response = redirect('common:home')
    return response

centr_osvita/templates/web/biology.html
{% extends "base.html" %} {% load static i18n %} {% block title %}Біологія
- ЦОТ{% endblock %} {% block content %}
<main>
  <section class="subject-section biology-section">
    <div class="content">
      <div class="subject-page">
        <h1>Біологія</h1>
        <div class="subject__body">
          <div class="subject__info">
            <div class="subject__points">
              <div class="subject__point">
                <img
                        src="{% static 'images/icons/book.png' %}"
                        alt="Програма"
                />
                <p>
                  Програма тренінгу охоплює зміст шкільного курсу біології
                </p>
              </div>
              <div class="subject__point">
                <img
                        src="{% static 'images/icons/clock.png' %}"
                        alt="Тривалість"
                />
                <p>Заняття триває 2 години</p>
              </div>
              <div class="subject__point">
                <img
                        src="{% static 'images/icons/calendar.png' %}"
                        alt="Тривалість"
                />
                <p>Одне заняття на тиждень</p>
              </div>
            </div>
            {% if user.is_authenticated %}
              <a href="/quiz/list?subject=biology" class="button">Пройти вхідний тест</a>
            {% endif %}
          </div>
          <div class="subject__teacher">
            <div class="teacher-card">
              <div class="teacher-card__info">
                <span>Викладач</span>
                <h4>Ткачук Олександр Іванович</h4>
                <a href="#" class="button button--stat">Статистика попередніх років</a>
              </div>
              <div class="teacher-card__photo">
                <img
                        src="{% static 'images/teachers/tkachuk_olexander.jpg' %}"
                        alt="Такачук Олександр Іванович"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>
{% endblock %}

centr_osvita/templates/web/chemistry.html
{% extends "base.html" %} {% load static i18n %} {% block title %}Хімія
- ЦОТ{% endblock %} {% block content %}
<main>
  <section class="subject-section chemistry-section">
    <div class="content">
      <div class="subject-page">
        <h1>Хімія</h1>
        <div class="subject__body">
          <div class="subject__info">
            <div class="subject__points">
              <div class="subject__point">
                <img
                        src="{% static 'images/icons/book.png' %}"
                        alt="Програма"
                />
                <p>
                  Програма тренінгу охоплює зміст шкільного курсу хімії 7-11 класів
                </p>
              </div>
              <div class="subject__point">
                <img
                        src="{% static 'images/icons/clock.png' %}"
                        alt="Тривалість"
                />
                <p>Заняття триває 2 години</p>
              </div>
              <div class="subject__point">
                <img
                        src="{% static 'images/icons/calendar.png' %}"
                        alt="Тривалість"
                />
                <p>Одне заняття на тиждень</p>
              </div>
            </div>
            {% if user.is_authenticated %}
              <a href="/quiz/list?subject=chemistry" class="button">Пройти вхідний тест</a>
            {% endif %}
          </div>
          <div class="subject__contacts">
            <div class="subject__contacts-head">
              Наші контакти
            </div>
            <div class="subject__contacts-body">
              <div class="subject__contacts-item">
                <div class="subject__contacts-icon">
                  <img src="{% static 'images/icons/phone.png' %}" alt="Phone" />
                </div>
                <div class="subject__contacts-info">
                  <p><a href="tel:+380982072728">(098) 207-27-28</a></p>
                  <p><a href="tel:+380938144042">(093) 814-40-42</a></p>
                </div>
              </div>
              <div class="subject__contacts-item">
                <div class="subject__contacts-icon">
                  <img
                          src="{% static 'images/icons/telegram.png' %}"
                          alt="Telegram"
                  />
                </div>
                <div class="subject__contacts-info">
                  <p>Telegram: <a href="tg://resolve?domain=cotvin">@cotvin</a></p>
                  <p><a href="tel:+380982072728">(098) 207-27-28</a></p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>
{% endblock %}

centr_osvita/templates/web/home.html
{% extends "base.html" %} {% load static i18n %} {% block title %}ЗНО -
ЦОТ{%endblock %} {% block content %}
<main>
  <section class="top-section">
    <div class="top-section-inner">
      <div class="content">
        <div class="top">
          <div class="top__info">
            <h1>Центр освітніх технологій</h1>
            <ul>
              <li>Тренінги для учнів та вчителів</li>
              <li>Пробне тестування</li>
              <li>Посібники для підготовки до ДПА та ЗНО</li>
            </ul>
            {% if not user.is_authenticated %}
            <a href="{% url 'users:register' %}" class="button button--adaptive"
            >Зареєструватись</a
            >
            {% endif %}
          </div>
        </div>
      </div>
    </div>

  </section>
  <section class="subjects-section" id="subjects">
    <div class="content">
      <div class="subjects">
        <h2>Обирай предмет</h2>
        <div class="subjects__items">
          <div class="subject">
            <img
              src="{% static 'images/icons/math.png' %}"
              alt="Math"
              class="subject__icon"
            />
            <span class="subject__title">Математика</span>
            <a href="{% url 'common:math' %}" class="button button--subject">Детальніше</a>
          </div>
          <div class="subject">
            <img
              src="{% static 'images/icons/ukr_lang.png' %}"
              alt="Math"
              class="subject__icon"
            />
            <span class="subject__title">Українська мова</span>
            <a href="{% url 'common:ukrainian' %}" class="button button--subject">Детальніше</a>
          </div>
          <div class="subject">
            <img
              src="{% static 'images/icons/eng_lang.png' %}"
              alt="Math"
              class="subject__icon"
            />
            <span class="subject__title">Англійська мова</span>
            <a href="{% url 'common:english' %}" class="button button--subject">Детальніше</a>
          </div>
          <div class="subject">
            <img
              src="{% static 'images/icons/history.png' %}"
              alt="Math"
              class="subject__icon"
            />
            <span class="subject__title">Історія</span>
            <a href="{% url 'common:history' %}" class="button button--subject">Детальніше</a>
          </div>
          <div class="subject">
            <img
              src="{% static 'images/icons/physics.png' %}"
              alt="Physics"
              class="subject__icon"
            />
            <span class="subject__title">Фізика</span>
            <a href="{% url 'common:physics' %}" class="button button--subject">Детальніше</a>
          </div>
          <div class="subject">
            <img
              src="{% static 'images/icons/geography.png' %}"
              alt="Geography"
              class="subject__icon"
            />
            <span class="subject__title">Географія</span>
            <a href="{% url 'common:geography' %}" class="button button--subject">Детальніше</a>
          </div>
          <div class="subject">
            <img
              src="{% static 'images/icons/biology.png' %}"
              alt="Biology"
              class="subject__icon"
            />
            <span class="subject__title">Біологія</span>
            <a href="{% url 'common:biology' %}" class="button button--subject">Детальніше</a>
          </div>
          <div class="subject">
            <img
              src="{% static 'images/icons/chem.png' %}"
              alt="Chemistry"
              class="subject__icon"
            />
            <span class="subject__title">Хімія</span>
            <a href="{% url 'common:chemistry' %}" class="button button--subject">Детальніше</a>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="about-section">
    <div class="content">
      <div class="about">
        <div class="about__info">
          <h2>Про наш центр</h2>
          <p>
            Вінницький обласний “Центр освітніх технологій” створено 2009 року.
            Основні види діяльності - проведення освітніх семінарів та тренінгів
            для учителів, батьків, студентів та учнів Вінницької області.
          </p>
          <p>
            Найбільші досягнення наша команда має у професійній підготовці
            старшокласників до здачі державної підсумкової атестації та
            незалежного оцінювання.
          </p>
          <p>
            За роки своєї діяльності Центр освітніх технологій отримав заслужене
            визнання серед дітей, їхніх батьків та учителів міста Вінниці й
            Вінницької області. У центрі працюють високопрофесійні спеціалісти з
            багатолітнім стажем роботи у школі та вищих навчальних закладах.
          </p>
          <p>
            На сьогодні наші викладачі готують випускників до здачі тестів ЗНО з
            усіх предметів. Тут можна отримати кваліфіковану консультацію з
            будь-яких питань, що стосуються навчальних програм пробного
            тестування, посібників для підготовки до тестів ЗНО, реєстрації на
            сайті Центру оцінювання якості освіти, вибору вузу та подачі
            документів під час вступу.
          </p>
          <p>
            Центр освітніх технологій займається інформаційно-видавничою
            діяльністю, співпрацює з міжнародними організаціями, сприяє
            поширенню інформації серед педагогів, тренерів та молоді про
            демократичну та громадянську освіту. Ми вивчаємо культурну спадщину
            українського народу та репрезентуємо матеріали на всеукраїнському та
            міжнародному рівнях
          </p>
        </div>
        <div class="about__img">
          <img src="{% static 'images/img-about-us.png' %}" alt="About us" />
          <div class="about__img-bg"></div>
        </div>
      </div>
    </div>
  </section>
  <section class="contacts-section" id="contacts">
    <div class="content">
      <div class="contacts-block">
        <div class="contacts">
          <h2>Наші контакти</h2>
          <div class="contacts__items">
            <div class="contacts__item">
              <div class="contacts__icon">
                <img src="{% static 'images/icons/phone.png' %}" alt="Phone" />
              </div>
              <div class="contacts__info">
                <p><a href="tel:+380982072728">(098) 207-27-28</a></p>
                <p><a href="tel:+380938144042">(093) 814-40-42</a></p>
              </div>
            </div>
            <div class="contacts__item">
              <div class="contacts__icon">
                <img src="{% static 'images/icons/viber.png' %}" alt="Viber" />
              </div>
              <div class="contacts__info">
                <p>Viber:</p>
                <p><a href="tel:+380938144042">(093) 814-40-42</a></p>
              </div>
            </div>
            <div class="contacts__item">
              <div class="contacts__icon">
                <img
                  src="{% static 'images/icons/telegram.png' %}"
                  alt="Telegram"
                />
              </div>
              <div class="contacts__info">
                <p>Telegram: <a href="tg://resolve?domain=cotvin">@cotvin</a></p>
                <p><a href="tel:+380982072728">(098) 207-27-28</a></p>
              </div>
            </div>
            <div class="contacts__item">
              <div class="contacts__icon">
                <img src="{% static 'images/icons/pin.png' %}" alt="Location" />
              </div>
              <div class="contacts__info">
                <p>м. Вінниця</p>
                <p>вул. Князів Коріатовичів 54, 21000</p>
              </div>
            </div>
            <div class="contacts__item">
              <div class="contacts__icon">
                <img src="{% static 'images/icons/phone.png' %}" alt="Phone" />
              </div>
              <div class="contacts__info">
                <p><a href="mailto:cot.vn.ua@gmail.com">cot.vn.ua@gmail.com</a></p>
              </div>
            </div>
          </div>
        </div>
        <div class="map">
          <img src="{% static 'images/map.jpg' %}" alt="Map" />
        </div>
      </div>
    </div>
  </section>
</main>

{% endblock %}